export const EXPENSES_LOADING = 'EXPENSES_LOADING';
export const EXPENSES_ERROR = 'EXPENSES_ERROR';
export const EXPENSES_FETCHED = 'EXPENES_FETCHED';

export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';

export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const GET_BUDGET = 'GET_BUDGET';