export const USER_REGISTERED = 'USER_REGISTERED';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const REGISTRATION_LOADING = 'REGISTRATION_LOADING';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const FETCH_EXPENSE = 'FETCH_EXPENSE';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const LOADING_EXPENSES = 'LOADING_EXPENSEs';
export const EXPENSES_ERROR = 'EXPENSES_ERROR';
export const EXPENSE_CRUD_ERROR = 'EXPENSE_CRUD_ERROR';

export const FETCH_BUDGET = 'FETCH_BUDGET';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const LOADING_BUDGET = 'LOADING_BUDGET';
export const BUDGET_ERROR = 'BUDGET_ERROR';
